version: '3'

services: 
  nodejs:
    build: 
      context: ./
      dockerfile: Dockerfile
      network: host
    image: filipedtristao/app
    container_name: app
    ports:
      - "3333:3333"
    entrypoint: dockerize -wait tcp://db:5432 -timeout 120s npm run serve
    networks:
      - node-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge